### ISSUE TITLE
6 individuals in LBBG_ZEEBRUGGE without tracking data

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#133]
- [x] 5038, L909202: ZEEB_KLVL | No tracking data received.
- [x] 5136, L909374: VLIS_THER
- [x] 5206, L907411: VLIS_THER | No tracking data received.
- [x] 5338, 5465451: VLIS_EPZ | Tracker reused from L911116.
- [x] 5492, L925726: ZEEB_BUS | No tracking data received.
- [x] 5546, L917359: ZEEB_KLVL | No or few tracking data within track session.

**Comment by peterdesmet** [comment]
@EricStienen

5136 has only 2 detections, at 2015-05-22 16:53:45 and 2015-05-22 17:26:18, which fall before the tracking start date of 2015-05-22 19:30:00 UTC. Can I update the remark to say `No tracking data within track session.`?

5338 has its last detection on 2016-05-29 23:57:04 (which is associated with individual L911116, with tracking end date of 2016-05-30 00:00:00 UTC). There are no detections within the tracking session for 5465451, starting at 2016-05-31 12:00:00 UTC. Can I update the remark to say `Tracker reused from L911116, No tracking data within track session.`?

**Comment by EricStienen** [comment]
yes you can
