### ISSUE TITLE
Move metadata to Google Spreadsheets

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#54]
Cf. fish tracking network.
## Fields
- [x] cartodb_id: number
- [x] the_geom: geometry
- [x] bird_name: string
- [x] catch_location: string
- [x] catch_weight: number
- [x] colour_ring_code: string
- [x] device_info_serial: number
- [ ] is_active: boolean
- [x] latitude: number, renamed
- [x] longitude: number, renamed
- [x] project_leader: string
- [x] remarks: string
- [x] ring_code: string
- [x] scientific_name: string
- [x] sex: string
- [x] species_code: string
- [x] tracking_ended_at: date
- [x] tracking_started_at: date
- [x] created_at: date
- [x] updated_at: date
## Tasks
- [x] Update table in SQL queries
- [x] Update latitude/longitude in documentation
- [x] Update latitude/longitude in SQL queries
- [x] Update is_active in SQL queries
